version: "3.8"

services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "666:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    command: sh -c "npm run build && npm start"
